import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
ADMIN_ID = int(os.getenv("ADMIN_ID"))

DATABASE_NAME = "database.db"

SUPPORT_USERNAME = "@subsmartbd"

FORCE_JOIN_ENABLED = True
FORCE_JOIN_CHANNEL = "@subsmaart"
FORCE_JOIN_LINK = "https://t.me/subsmaart"

REFERRAL_REWARD = 0.05
MINIMUM_DEPOSIT = 0.20

USD_RATE = 130.0

BKASH_NUMBER = "01985405068"
NAGAD_NUMBER = "01613305454"
ROCKET_NUMBER = "01985405068"

BKASH_CASHOUT = 1.85
NAGAD_CASHOUT = 1.49
ROCKET_CASHOUT = 14.49

BINANCE_USERNAME = "YOUR_BINANCE_USERNAME"
BYBIT_USERNAME = "YOUR_BYBIT_USERNAME"
